package com.oblong.marvel.model;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public enum PhysicalForm {

    HumanNormal("Human (Normal)", 2, 0.27){
        public int getResourcesBonus(){ return 1; }
        public String getNotes(){ return "<b>Normal Human</b>: The body is completely normal and possesses no detectable abnormalities.  Any Powers the hero possesses have left no visible mark on the body."; }
    },
    MutantInduced("Mutant (Induced)", 1, 0.05){
        public int getBonusAbilityRanks(){ return 1; }
        public String getNotes(){ return "<b>Induced Mutant</b>: The hero started life as a Normal Human, \"then something happened.\" As a result of a freak happenstance, the hero has been physically and genetically altered. The Fantastic Four are examples of this type."; }
    },
    MutantRandom("Mutant (Random)", 1, 0.03){
        public int getResourcesBonus(){ return -1; }
        public int getEnduranceBonus(){ return 1; }
        public int getNumberOfPowersBonus(){ return 1; }
        public String getNotes(){ return "<b>Random Mutation</b>: The hero was born to Normal Humans, but a freak twist of genetic fate made him a mutant from birth. Most of these are the Mutants found in the Marvel Universe, such as the X-Men."; }
    },
    MutantBreed("Mutant (Breed)", 1, 0.02){
        public int getEnduranceBonus(){ return 1; }
        public int getIntuitionBonus(){ return 1; }
        public List<Contact> getForcedContacts(){ return new ArrayList<Contact>(Collections.singletonList(new Contact("Tribe/Family"))); }
        public String getNotes(){ return "<b>Breed Mutants</b>: The hero's parents were Mutants, as were any number of preceding generations. Breed Mutants form tribes and have close-knit families; this is a defense mechanism born from generations spent hiding their true selves from normal society. Examples of Breed Mutants include the Inhumans."; }
    },
    Android("Android", 4, 0.03){
        public int getPopularityBonus(){ return -1; }
        public int getNumberOfPowersBonus(){ return 1; }
        public int getBonusAbilityRanks(){ return 1; }
        public List<Contact> getForcedContacts(){ return new ArrayList<Contact>(Collections.singletonList(new Contact("Creator"))); }
        public String getNotes(){ return "<b>Androids</b>: These are artificially created organic beings. An android is made of laboratory-created protoplasm and grows to maturity in an artificial womb. More intricately made Androids can actually interbreed with Normal Humans. One example is the Vision. Androids generally resemble the race that created them; alien androids can be any shape."; }
    },
    HumanoidRace("Humanoid Race", 5, 0.07){
        public int getBonusAbilityRanks(){ return 1; }
        public List<Perk> getPerks(){ return new ArrayList<Perk>(Arrays.asList(Perk.PoorResources)); }
        public List<Contact> getForcedContacts(){ return new ArrayList<Contact>(Collections.singletonList(new Contact("Race"))); }
        public String getNotes(){ return "<b>Humanoid Race</b>: The hero is a normal member of a human-like race from \"somewhere else.\" This may be another world, era, dimension, or lost land hidden somewhere on the Earth. Most can pass as Normal Humans with a little disguise or explanation. Some of the Humanoid Race's Powers don't exist in their home environment but develop as a result of the Humanoid's exposure to Earth's environment."; }
    },
    SurgicalComposite("Surgical Composite", 2, 0.01){
        public int getFightingBonus(){ return 1; }
        public int getStrengthBonus(){ return 1; }
        public int getEnduranceBonus(){ return 1; }
        public List<Perk> getPerks(){ return new ArrayList<Perk>(Arrays.asList(Perk.PoorResources)); }
        public List<Contact> getForcedContacts(){ return new ArrayList<Contact>(Collections.singletonList(new Contact("Creator"))); }
        public String getNotes(){ return "<b>Surgical Composites</b>: The hero was created in an operating room. His body contains parts taken from several bodies.  Close examination reveals the scars from his creation. The most famous example is Adam, the Frankenstein Monster.  Because of the widespread knowledge of that story, Surgical Composites are feared more than Mutants. They also possess a morbid curiosity about the people whose parts now form their bodies. Resistance to Mental Domination is reduced -1CS.  Composites heal twice as quickly as Normal Humans.  The Composite initially possesses one the hospital or person responsible for his creation."; }
    },
    ModifiedHumanOrganic("Modified Human (Organic)", 1, 0.02){
        public int getNumberOfPowersBonus(){ return -1; }
        public List<Contact> getForcedContacts(){ return new ArrayList<Contact>(Collections.singletonList(new Contact("Modifier"))); }
        public String getNotes(){ return "<b>Modified Human</b>: This is someone who started life as a Normal Human and was later altered by some means. The change affected his body on a physical level but did not alter his DNA. Genetically, the hero is still very much human and cannot pass on his Powers to his descendants.  Organic Modification means the hero's internal organs and nervous system have been altered. Perhaps he now possesses new organs or glands that are the basis for what Powers he has.  Organics heal twice as fast as Normal Humans.  At least one Contact should be the organization responsible for the modification."; }
    },
    ModifiedHumanMuscular("Modified Human (Muscular)", 1, 0.02){
        public int getStrengthBonus(){ return 1; }
        public int getEnduranceBonus(){ return 1; }
        public int getNumberOfPowersBonus(){ return -1; }
        public List<Contact> getForcedContacts(){ return new ArrayList<Contact>(Collections.singletonList(new Contact("Modifier"))); }
        public String getNotes(){ return "<b>Modified Human</b>: This is someone who started life as a Normal Human and was later altered by some means. The change affected his body on a physical level but did not alter his DNA. Genetically, the hero is still very much human and cannot pass on his Powers to his descendants.  Muscular Modification is easy to detect; just look for a person with outrageous muscular development. Captain America is a good example of this.  At least one Contact should be the organization responsible for the modification."; }
    },
    ModifiedHumanSkeletal("Modified Human (Skeletal)", 1, 0.02){
        public int getNumberOfPowersBonus(){ return -1; }
        public List<Contact> getForcedContacts(){ return new ArrayList<Contact>(Collections.singletonList(new Contact("Modifier"))); }
        public String getNotes(){ return "<b>Modified Human</b>: This is someone who started life as a Normal Human and was later altered by some means. The change affected his body on a physical level but did not alter his DNA. Genetically, the hero is still very much human and cannot pass on his Powers to his descendants.  Skeletal Modification means the hero's original skeletal structure has been replaced or augmented by artificial means. Although he is also a Random Mutant, Wolverine is a good example of this type of character. The new skeleton can be crammed with various things that can give the hero his Powers. At least one Contact should be the organization responsible for the modification."; }
    },
    ModifiedHumanExtraParts("Modified Human (Extra Parts)", 1, 0.04){
        public String getNotes(){ return "<b>Modified Human</b>: This is someone who started life as a Normal Human and was later altered by some means. The change affected his body on a physical level but did not alter his DNA. Genetically, the hero is still very much human and cannot pass on his Powers to his descendants.  This type of body is harder to disguise than the other Modifications because the body now possesses extra pieces of anatomy.  These may be duplicates of normal parts arms are probably the most common example), or parts that are not found on a Normal Human. Such new parts include wings, tails, antennae, fins, or anything else that might create Powers for the hero.  Humans with Extra Parts roll on column 1.  Arms raise Fighting +1CS.  Duplicate organs doubles the Health point total.  Tails give the hero an additional attack when engaged in blunt attacks (1 per tail).  Wings give the hero Flight."; }
    },
    DemihumanCentaur("Demihuman (Centaur)", 5, 0.01){
        public int getStrengthBonus(){ return 1; }
        public String getNotes(){ return "<b>Demihumans</b>: This covers a range of human-like beings who combine the physical traits of humans and animals.  Demihumans can be unique individuals or members of a race that inhabits a different place or time. Because of the wealth of legends surrounding demihumans, a new character of this type finds that his Popularity is influenced by people's preconceived notions and biases toward things with his shape.  Centaurs have a human head, torso, and arms mated to the body of a horse.  They possess increased Strength (+1CS), can move quickly over horizontal ground (four areas/turn), and can fight with their hooves. On the minus side, centaurs have Feeble Climbing ability.  They are popularly thought of as scholars or drunken lechers."; }
    },
    DemihumanEquiman("Demihuman (Equiman)", 3, 0.01){
        public String getNotes(){ return "<b>Demihumans</b>: This covers a range of human-like beings who combine the physical traits of humans and animals.  Demihumans can be unique individuals or members of a race that inhabits a different place or time. Because of the wealth of legends surrounding demihumans, a new character of this type finds that his Popularity is influenced by people's preconceived notions and biases toward things with his shape.  Equimen possess horse legs in place of human ones. They have a horse's mane and tail as well. Such beings are often confused with fauns, although equimen lack horns. An equiman is born from two equimen, or from a centaur mating with a human. By hiding the legs and tail, an equiman can pass for human. Kicking does +1CS damage."; }
    },
    DemihumanFaun("Demihuman (Faun)", 2, 0.01){
        public List<Perk> getPerks(){ return new ArrayList<Perk>(Arrays.asList(Perk.Unpopular)); }
        public List<Power> getForcedPowers(){ return new ArrayList<Power>(Arrays.asList(
                    new Power(Power.PowerType.MindControl, AbilityRank.Feeble))); }
        public String getNotes(){ return "<b>Demihumans</b>: This covers a range of human-like beings who combine the physical traits of humans and animals.  Demihumans can be unique individuals or members of a race that inhabits a different place or time. Because of the wealth of legends surrounding demihumans, a new character of this type finds that his Popularity is influenced by people's preconceived notions and biases toward things with his shape.  Fauns possess the hairy legs, short tail, and horns of a goat. They are frequently confused with either equimen, who are taller, or with the traditional image of a devil. Because of the unfortunate resemblance to the latter, fauns have an initial Popularity of zero.  They possess Feeble Mental Domination over females of any human(oid) race, which, coupled with their penchant for intoxication, causes them to gain Popularity more slowly than other Demihumans."; }
    },
    DemihumanFelinoid("Demihuman (Felinoid)", 1, 0.02){
        public List<Power> getForcedPowers(){ return new ArrayList<Power>(Arrays.asList(
                    new Power(Power.PowerType.ThermalVision, AbilityRank.Excellent))); }
        public String getNotes(){ return "<b>Demihumans</b>: This covers a range of human-like beings who combine the physical traits of humans and animals.  Demihumans can be unique individuals or members of a race that inhabits a different place or time. Because of the wealth of legends surrounding demihumans, a new character of this type finds that his Popularity is influenced by people's preconceived notions and biases toward things with his shape.  Felinoids are human-shaped, cat-like beings. The overall body shape is human, but the skin is covered in fur and the face is that of a cat. A felinoid has a tail, claws, fangs, pointed ears on top of the head, and slitted pupils in the eyes. A felinoid can see in the dark with Excellent night vision. Such beings possess +1CS Climbing ability. Tigra is a good example."; }
    },
    DemihumanLupinoid("Demihuman (Lupinoid)", 4, 0.02){
        public int getPopularityBonus(){ return -1; }
        public String getNotes(){ return "<b>Demihumans</b>: This covers a range of human-like beings who combine the physical traits of humans and animals.  Demihumans can be unique individuals or members of a race that inhabits a different place or time. Because of the wealth of legends surrounding demihumans, a new character of this type finds that his Popularity is influenced by people's preconceived notions and biases toward things with his shape.  Lupinoids are human-shaped, caninelike beings. They are often mistaken for the cinematic conception of a werewolf.  The body is covered in hair and the face is definitely canine. The body has a tail, harmless claws, big teeth, and long pointed ears atop the head. A lupinoid possesses an Excellent sense of smell.  The Popularity of lupinoids varies.  Because some people think every lupinoid is a werewolf, their Popularity decreases -1CS. Other people see them as dogs, and thus as man's best friend; this prevents the Popularity from dropping any further. Lupinoid genetics are the most flexible of all the demihumans. There are as many breeds of lupinoids as there are of dogs, wolves, and foxes (the latter being a subclass, the vulpinoid)."; }
    },
    DemihumanAvianAngelic("Demihuman (Angelic Avian)", 1, 0.01){
        public int getPopularityBonus(){ return 1; }
        public String getNotes(){ return "<b>Demihumans</b>: This covers a range of human-like beings who combine the physical traits of humans and animals.  Demihumans can be unique individuals or members of a race that inhabits a different place or time. Because of the wealth of legends surrounding demihumans, a new character of this type finds that his Popularity is influenced by people's preconceived notions and biases toward things with his shape.  Avians come in two basic types, angels and harpies.  The angelic avians resemble humans with wings sprouting from the shoulder blades. Angel of XFactor is this type. They get an increased Popularity (+1CS).  Angelic avians reproduce by normal human means."; }
    },
    DemihumanAvianHarpy("Demihuman (Harpy)", 1, 0.01){
        public int getFightingBonus(){ return 1; }
        public String getNotes(){ return "<b>Demihumans</b>: This covers a range of human-like beings who combine the physical traits of humans and animals.  Demihumans can be unique individuals or members of a race that inhabits a different place or time. Because of the wealth of legends surrounding demihumans, a new character of this type finds that his Popularity is influenced by people's preconceived notions and biases toward things with his shape.  Avians come in two basic types, angels and harpies.  Harpies possess arms that are modified to also serve as wings and feather- covered legs that end in bird claws. They gain +1CS Fighting.  Harpies lay eggs."; }
    },
    DemihumanChiropteran("Demihuman (Chiropteran)", 1, 0.01){
        public List<Perk> getPerks(){ return new ArrayList<Perk>(Arrays.asList(Perk.FeeblePopularity)); }
        public List<Power> getForcedPowers(){ return new ArrayList<Power>(Arrays.asList(
                    new Power(Power.PowerType.Sonar, AbilityRank.Good))); }
        public String getNotes(){ return "<b>Demihumans</b>: This covers a range of human-like beings who combine the physical traits of humans and animals.  Demihumans can be unique individuals or members of a race that inhabits a different place or time. Because of the wealth of legends surrounding demihumans, a new character of this type finds that his Popularity is influenced by people's preconceived notions and biases toward things with his shape.  Chiropterans are similar to angelic humans except that they combine the human parts with those of a bat. Their arms also serve as leathery wings, their feet have elongated toes that can serve as hands, and in addition they possess large ears. They possess the Power of Active Sonar at Good rank. 'Pterans scare most people, especially the bulk of the populace who believe all bats are Vampires. Initial Popularity is Feeble."; }
    },
    DemihumanLamian("Demihuman (Lamian)", 1, 0.005){
        public List<Perk> getPerks(){ return new ArrayList<Perk>(Arrays.asList(Perk.Unpopular)); }
        public String getNotes(){ return "<b>Demihumans</b>: This covers a range of human-like beings who combine the physical traits of humans and animals.  Demihumans can be unique individuals or members of a race that inhabits a different place or time. Because of the wealth of legends surrounding demihumans, a new character of this type finds that his Popularity is influenced by people's preconceived notions and biases toward things with his shape.  Lamians are snake people. The legs have been replaced by a serpentine body, although the arms are normal. The skin is covered in fine scales. Lamians have lidless eyes and retractable fangs.  Because snakes terrify so many people, the lamian's initial Popularity is zero.  Lamians are difficult to bind (+1CS to escape)."; }
    },
    DemihumanLamianVenomous("Demihuman (Lamian, Venomous)", 1, 0.005){
        public List<Perk> getPerks(){ return new ArrayList<Perk>(Arrays.asList(Perk.Unpopular)); }
        public String getNotes(){ return "<b>Demihumans</b>: This covers a range of human-like beings who combine the physical traits of humans and animals.  Demihumans can be unique individuals or members of a race that inhabits a different place or time. Because of the wealth of legends surrounding demihumans, a new character of this type finds that his Popularity is influenced by people's preconceived notions and biases toward things with his shape.  Lamians are snake people. The legs have been replaced by a serpentine body, although the arms are normal. The skin is covered in fine scales. Lamians have lidless eyes and retractable fangs.  The lamian is venomous (Excellent Intensity poison).  Because snakes terrify so many people, the lamian's initial Popularity is zero.  Lamians are difficult to bind (+1CS to escape)."; }
    },
    DemihumanMerhuman("Demihuman (Merhuman)", 2, 0.01){
        public int getPopularityBonus(){ return 1; }
        public List<Power> getForcedPowers(){ return new ArrayList<Power>(Arrays.asList(
                    new Power(Power.PowerType.WaterFreedom, AbilityRank.Good))); }
        public String getNotes(){ return "<b>Demihumans</b>: This covers a range of human-like beings who combine the physical traits of humans and animals.  Demihumans can be unique individuals or members of a race that inhabits a different place or time. Because of the wealth of legends surrounding demihumans, a new character of this type finds that his Popularity is influenced by people's preconceived notions and biases toward things with his shape.  Merhumans are amphibious relatives of lamians. The body is human from the waist up; the rest is a flexible fish-tail. Merhumans possess both lungs and gills, but can only stay away from water a limited time because their bodies quickly dry out. Movement on dry land is limited to crawling or dependence on vehicles. Merhumans also possess Water Freedom. They fascinate Normal Humans and have an increased Popularity (+1CS). The usefulness of a merhuman in a land-locked campaign is limited, but certain Powers can overcome the merhuman's disadvantages - Shapechange, Alter Ego, True Flight, and so on."; }
    },
    DemihumanOther("Demihuman (Other)", 1, 0.01){
        public String getNotes(){ return "<b>Demihumans</b>: This covers a range of human-like beings who combine the physical traits of humans and animals.  Demihumans can be unique individuals or members of a race that inhabits a different place or time. Because of the wealth of legends surrounding demihumans, a new character of this type finds that his Popularity is influenced by people's preconceived notions and biases toward things with his shape.  There are numerous other Demihumans you could create. The player can combine any animal with a human to create a new Demihuman, then work with the Judge to provide it with reasonable statistics."; }
    },
    CyborgArtificialLimbsOrgans("Cyborg (Artificial Limbs & Organs)", 1, 0.02){
        public int getIntuitionBonus(){ return -1; }
        public List<Contact> getForcedContacts(){ return new ArrayList<Contact>(Collections.singletonList(new Contact("Creator"))); }
        public String getNotes(){ return "<b>Cyborg</b>: While most cyborgs are High Tech creations, there are also Magical Cyborgs. For example, the Celtic god Nuada had an arm made of silver. The player should determine what parts are artificial, using the randomly generated Abilities and Powers as a guide. For example, Strength of Remarkable or better suggests the limbs and skeleton are artificial. Speed-running could come from a leg-replacement. Vision Powers seem to require at least one man-made eye. At least one Contact must be either the lab or hospital that created him of a facility that provides maintenance services.  Limb and Organ: The hero began as a Normal Human but has had parts of his body replaced by artificial devices. This may have been done to save the hero's life after a near-fatal accident or the hero may have voluntarily undergone the operation in order to gain Powers. The original Deathlok is an example of the former type. Cyborgs initially have a decreased Intuition (-1CS) due to mental anguish over a perceived loss of humanity (in the former case) or a self-hatred toward their original weak human form (in the latter)."; }
    },
    CyborgExoskeleton("Cyborg (Exoskeleton)", 1, 0.02){
        public String getNotes(){ return "<b>Cyborg</b>: While most cyborgs are High Tech creations, there are also Magical Cyborgs. For example, the Celtic god Nuada had an arm made of silver. The player should determine what parts are artificial, using the randomly generated Abilities and Powers as a guide. For example, Strength of Remarkable or better suggests the limbs and skeleton are artificial. Speed-running could come from a leg-replacement. Vision Powers seem to require at least one man-made eye. At least one Contact must be either the lab or hospital that created him of a facility that provides maintenance services.  Exoskeletons: The hero's body is intact but is encased in a mechanical suit that provides him with life-support and Powers. The natural and artificial bodies exist in symbiosis. Tony Stark/iron Man is the perfect example of this.  The most common Exoskeletons are roughly the same size and shape as the being within; that is, the Exoskeleton resembles a clunky suit of armor.  Exoskeletons can come in any size of shape, however. The giant robots of Japanese cartoons are actually immense Cyborg Exoskeletons."; }
    },
    CyborgMechanicalBody("Cyborg (Mechanical Body)", 4, 0.02){
        public int getIntuitionBonus(){ return -1; }
        public int getPsycheBonus(){ return -1; }
        public List<Contact> getForcedContacts(){ return new ArrayList<Contact>(Collections.singletonList(new Contact("Creator"))); }
        public List<Perk> getPerks(){ return new ArrayList<Perk>(Arrays.asList(Perk.JustOneFriend)); }
        public String getNotes(){ return "<b>Cyborg</b>: While most cyborgs are High Tech creations, there are also Magical Cyborgs. For example, the Celtic god Nuada had an arm made of silver. The player should determine what parts are artificial, using the randomly generated Abilities and Powers as a guide. For example, Strength of Remarkable or better suggests the limbs and skeleton are artificial. Speed-running could come from a leg-replacement. Vision Powers seem to require at least one man-made eye. At least one Contact must be either the lab or hospital that created him of a facility that provides maintenance services.  Mechanical Body: The only part of the hero's original body that remains is his brain and the nervous system. This is housed in a special life-support module that fills most of the brain's needs (oxygen, blood, nutrients). The life support module is mated with a mechanical form that serves the brain as its new body. The nervous system is directly linked with the machine's control circuits, allowing both control and sensory feedback.  Mech bodied characters are often mistaken for Pure Robots. In fact, an internal examination is needed to clearly distinguish the two types. Of course, Pure Robots don't feel the urge to cry. Mech bodies are even more morose than Mech Limb cyborgs; at least the latter retain some of their bodies. Their depression causes them to have a lower initial Intuition and Psyche (-1CS to both).  Mech Bodies have Monstrous Resistance to Disease and Poisons of all sorts. This is because the brain is doubly protected from the outside world.  However, they are prone to things that never harm a flesh-bound character, like Magnetic attacks and rust. When creating the hero, the player must decide what his Mech Body looks like. For most campaigns, the Mech Body is basically human- shaped. It may even have a pseudo-flesh covering to disguise the body's true nature. Such coverings tend not to survive battles, though, so the hero must have a spare supply. Replacing a full body cover has an Excellent cost; a head-and-handsonly set is a bargain of Good cost.  Mech Bodies can come in other shapes.  These can be anything the hero might find useful in his environment: spider-bots, baby tanks, starships, etc. Since specialized Mech Bodies are less adaptable, such characters tend to be NPCs. Mech Bodies are not limited to a single body, though. A lab with Remarkable facilities can adapt the life-support module for easy transferral to other bodies. Thus, your hero can have as many bodies as his Resources can provide.  If the Mech Body has different forms, the player must generate the Physical Abilities and Powers of additional bodies as if they were separate characters. Mech Bodies initially have only one Contact—the lab where they were created."; }
    },
    CyborgMechanicallyAugmented("Cyborg (Mechanically Augmented)", 3, 0.03){
        public int getNumberOfPowersBonus(){ return -1; }
        public String getNotes(){ return "<b>Cyborg</b>: While most cyborgs are High Tech creations, there are also Magical Cyborgs. For example, the Celtic god Nuada had an arm made of silver. The player should determine what parts are artificial, using the randomly generated Abilities and Powers as a guide. For example, Strength of Remarkable or better suggests the limbs and skeleton are artificial. Speed-running could come from a leg-replacement. Vision Powers seem to require at least one man-made eye. At least one Contact must be either the lab or hospital that created him of a facility that provides maintenance services.  Mechanical Augmentation: This is a Cyborg who still has all his original (human) equipment but carries some options inside. Unused spaces in his body are now filled with various useful devices. These can be directly controlled through the nervous system. It is these devices that give the hero his Powers. They can be anything from a, tiny radio in the ear to a Disintegration gun concealed in the arm.  Augmenteds chose their condition and do not suffer from the depression that affects most Cyborgs and Mech Bodies.  Since there is a limited amount of extra space in the body, Augmenteds receive one less Power.  If the hero possesses Hyper-Intelligence, Hyper-Invention, or Weapons Tinkering, then he may have created his new form himself with the help of a Remarkable clinic."; }
    },
    RobotHumanShape("Robot (Human-Shape)", 4, 0.03){
        public List<Perk> getPerks(){ return new ArrayList<Perk>(Arrays.asList(Perk.Unpopular)); }
        public String getNotes(){ return "<b>Pure Robot—Humanshape</b>: This is a completely mechanical being that is patterned after the human body. The degree of similarity varies; specimens can include metallic skinned caricatures (Sentinels), metallic simulations (Jocasta), and pseudo-fleshed imitations (Delphine Courtney). Most are High Tech but rare specimens are Magical in nature, clockwork men given life by eccentric mages.  While most Humanshapes are the size of Normal Humans, they are much heavier. The average specimen weighs 500 to 2,000 pounds.  Player character robots possess self-repair facilities that simulate normal Healing.  There is Karma loss if a hero purposely destroys a sentient robot.  Robots are people too. Non-sentient robots are cannon fodder."; }
    },
    RobotUsuform("Robot (Usuform)", 4, 0.02){
        public String getNotes(){ return "<b>Usuform Robot</b>: This is a robot that believes in the adage, \"Form follows function.\" This robot's body is anything but humanshaped and is designed to best serve specific needs. For the game's purposes, needs refers to Powers the usuform possesses.  Sentient usuforms are often mistaken for mindless industrial robots; people usually look for a human controller hiding nearby. Popularity is unaffected because people simply do not give the usuform any thought other than \"Oh, what a wild prop!\""; }
    },
    RobotMetamorphic("Robot (Metamorphic)", 4, 0.02){
        public String getNotes(){ return "<b>Metamorphic Robot</b>: This is a robot whose design is so flexible it can change into two or more forms, each possessing different Physical Abilities and Physical Powers. Most Metamorphs have a dual nature. The primary form is a humanshape; the secondary form may be a vehicle or usuform. Both forms weigh the same, but may be different sizes. A Metamorph can change into a form that is up to three times larger than the smaller form. If the metamorph possesses size-altering Powers, this limit is replaced by that Power's limit.  The player must generate separate Physical abilities for each form and assign Powers to either or both forms.  Metamorphs have a minimum of two forms. In the creation process, additional forms can be gained at a cost of -1CS to all Primary Abilities for each additional form gained."; }
        public String getPlayerNotes(){ return "The player needs to generate a number of forms and what those are for their Physical Form."; }
    },
    RobotComputer("Robot (Computer)", 4, 0.01){
        public int getFightingBonus(){ return -1; }
        public int getReasonBonus(){ return 2; }
        public int getResourcesBonus(){ return 1; }
        public String getNotes(){ return "<b>Computer</b>: The hero is a computer, period. At first glance this seems unplayable, but bear me out. This is a rare computer, one that is self-aware and possesses true intelligence. While the mainframe itself is immobile and unable to physically act, peripherals give the sentient computer a wide range of means to deal with the physical world. Slave robots act as proxies for the computer. Physical additions provide tile mainframe with add-on functions. The Computer can directly interact with other computers, robots, and some cyborgs on a programming level. In some campaigns, there may even be a computer-generated pocket dimension where computer programs are \"living\" beings. If the computer possesses Alter Ego or Lifeform Creation, it can create a human-like extension of itself. Such a being would possess all the computer's abilities and most of its Powers (save those assigned to the peripheral hardware). Damage to the extension results in feedback that causes equivalent damage to the mainframe.  The computer may hide its true nature and intelligence from its owners, creators, and/or programmers. Only a major threat to its existence can cause it to reveal itself and risk losing its freedom.  In a magical setting, the computer can be any mystical device, such as a crystal ball or an elaborate altar. Slave units and peripherals are likewise translated into mystical analogs.  For game purposes, assume that all sentient computers have a minimum of one remotely controlled industrial robot.  The owners think this robot is only used for self-maintenance and experimentation.  Resources represent company supplies directly controlled by the computer or those which it can order without arousing suspicion.  Computers have a decreased Resistance to Electrical and Magnetic Attacks and also to Phasing.  Loss of all electrical power to the mainframe causes deactivation and loss of some of the computer's abilities and all of its Karma. Abilities and Powers are reduced -1CS across the board."; }
    },
    Angel("Angel", 5, 0.005){
        public int getFightingBonus(){ return 1; }
        public int getAgilityBonus(){ return 1; }
        public int getStrengthBonus(){ return 1; }
        public int getEnduranceBonus(){ return 1; }
        public int getReasonBonus(){ return 1; }
        public int getIntuitionBonus(){ return 1; }
        public int getPsycheBonus(){ return 1; }
        public int getPopularityBonus(){ return 2; }
        public List<Perk> getPerks(){ return new ArrayList<Perk>(Arrays.asList(Perk.ExtraPsychologicalWeakness, Perk.AllAlone)); }
        public List<Power> getForcedPowers(){ return new ArrayList<Power>(Arrays.asList(
                new Power(Power.PowerType.ArtifactCreation, AbilityRank.Excellent) //a flaming sword
        )); }
        public String getNotes(){ return "<b>Angels</b>: These are magical beings from other planes of existence.  They are both supernatural and corporeal in nature. \"Angels\" are benevolent. These beings resemble characters from various mythologies. This affects their Popularity.  These beings do not necessarily follow the popular traditional behavior patterns. A crazed angel might be a villain, seeking to purify the Earth at any cost.  Angels have no initial Contacts but will soon be sought out by groups who see them as symbols or tools.  Angels automatically possess a specific form of Artifact Creation that produces a magical sword that does Excellent damage."; }
    },
    Demon("Demon", 5, 0.005){
        public int getFightingBonus(){ return 1; }
        public int getAgilityBonus(){ return 1; }
        public int getStrengthBonus(){ return 1; }
        public int getEnduranceBonus(){ return 1; }
        public int getReasonBonus(){ return 1; }
        public int getIntuitionBonus(){ return 1; }
        public int getPsycheBonus(){ return 1; }
        public int getPopularityBonus(){ return -2; }
        public List<Perk> getPerks(){ return new ArrayList<Perk>(Arrays.asList(Perk.ExtraPsychologicalWeakness, Perk.AllAlone)); }
        public List<Power> getForcedPowers(){ return new ArrayList<Power>(Arrays.asList(
                new Power(Power.PowerType.FireGeneration, AbilityRank.Good))); }
        public String getNotes(){ return "<b>Demons</b>: These are magical beings from other planes of existence.  They are both supernatural and corporeal in nature. \"Demons\" are malevolent. These beings resemble characters from various mythologies. This affects their Popularity.  These beings do not necessarily follow the popular traditional behavior patterns. A heroic demon might be fighting a personal war against other, even more evil beings. Demons have no initial Contacts but will soon be sought out by groups who see them as symbols or tools.  Demons automatically possess Good Fire Generation and Specific Invulnerability to Heat and Fire."; }
    },
    Deity("Deity", 5, 0.01){
        public int getFightingBonus(){ return 2; }
        public int getAgilityBonus(){ return 2; }
        public int getStrengthBonus(){ return 2; }
        public int getEnduranceBonus(){ return 2; }
        public int getReasonBonus(){ return 2; }
        public int getIntuitionBonus(){ return 2; }
        public int getPsycheBonus(){ return 2; }
        public int getPopularityBonus(){ return 2; }
        public int getNumberOfPowersBonus(){ return 2; }
        public List<Contact> getForcedContacts(){ return new ArrayList<Contact>(Collections.singletonList(new Contact("Worshippers"))); }
        public List<Perk> getPerks(){ return new ArrayList<Perk>(Arrays.asList(Perk.Traveller)); }
        public String getNotes(){ return "<b>Deity</b>: This is an \"Entity of Great Power\" - or rather, was such a being. The deity was an actual god, demigod, or close relative who was actually worshipped at some point in the past. Now his powers have waned because the religion which was devoted to him is no longer practiced. His followers have disappeared into the annals of history. Thor is an example of such a being. Now he is a god-on-Earth and locked into a mortal shell. He is still a formidable being, though. Deities have increased ranks in all their primary abilities and cannot really die in the Earth Dimension unless the slayer is another deity. Each deity has a home dimension; on that plane the deity loses his special protection from death. Deities are usable as player characters. The Marvel Universe includes Asgardians, Olympians, and deities from a host of other pantheons. Both Thor and Hercules are members of the Avengers.  Snowbird, daughter of an Inuit goddess, is a member of Alpha Flight. The thing that permits their playability is their diminished Power. Once Odin formed the Earth from the blood and bones of a slain Ice Giant, but he can't do things like that anymore.  There are three reasons a deity might be found on Earth. One is that his Powers have diminished to such a point that the Earth Dimension is the only place he can survive. The second is that he has been sent to the Earth Dimension by other, more powerful Deities. Both Thor and Snowbird are in this category. The third reason is that the deity is bored with timeless infinity and is slumming it on Earth as a way of generating excitement. Hercules fits this bill. Actually, there is also a fourth reason.  The deity might be on Earth seeking Power, whether by regaining worshippers or establishing a portal between Earth and his home dimension. However, for game purposes, this reason is restricted to NPC deities who are acting as villains in your campaign.  Deities have increased Popularity (+2CS) with the public but zero Popularity with the hierarchy of the major established Earth religions.  Deities eventually attract any remaining living worshippers they still have. All of these people serve as Contacts. A deity PC who abuses his worshippers faces a stiff Karma penalty. Deities are honor-bound not to actively promote a religion based on themselves.  Deity PCs who try this lose -1CS from all their Abilities and Powers."; }
    },
    Animal("Animal", 1, 0.01){
        public int getNumberOfPowersBonus(){ return -1; }
        public List<Perk> getPerks(){ return new ArrayList<Perk>(Arrays.asList(Perk.AnimalSenses)); }
        public String getNotes(){ return "<b>Animals</b>: This is a catch-all category that includes fish, mammals, birds, reptiles, and the rest of Earth's fauna, in addition to aliens that do not fit into any other category. About the only example of this in the Marvel Universe is Lockheed, the dragon. Your campaign, on the other hand, might be filled with heroic Animals or really peculiar aliens (I'll fudge a little and include Lockjaw, the Inhumans' \"dog\" as an example of this).  Animal PCs have three main types of backgrounds. One is that the animal is a mutant. Another is that the animal was altered in ways that gave his intelligence and Power. The last is the animal is a relatively normal member of a race of animals like him (Lockheed, for example).  The player can determine this in the Origins of Power section and embellish it to the best of his ability.  Animals have to have a human Contact. People tend to see the human Contact as the animal's owner or trainer.  People refuse initially to believe the animal is intelligent. Animals have very few legal rights, but they also have few responsibilities.  Animals risk death or capture from people who are ignorant of the animal's true nature.  Resources are zero unless the animal has attached himself to a human. In this case, the Resource rank is assigned to that human."; }
    },
    Vegetable("Vegetable", 1, 0.01){
        public int getFightingBonus(){ return -2; }
        public int getEnduranceBonus(){ return 2; }
        public List<Perk> getPerks(){ return new ArrayList<Perk>(Arrays.asList(Perk.ZeroResources, Perk.JustOneFriend)); }
        public List<Power> getForcedPowers(){ return new ArrayList<Power>(Arrays.asList(
                    new Power(Power.PowerType.Absorption, AbilityRank.Good) //photosynthesis
            )); }
        public List<Contact> getForcedContacts(){ return new ArrayList<Contact>(Collections.singletonList(new Contact("Creator"))); }
        public String getNotes(){ return "<b>Vegetable</b>: The hero is an intelligent, mobile plant. He can be of any nature but for game purposes the hero is assumed to be a man- shaped plant. His physiology is based on photosynthesis.  The plant-man doesn't need to eat anything except a bit of fertilizer occasionally. Prolonged deprivation of light and water reduces the hero's Strength and Endurance -1CS per day after an initial three days. Plants have no legal rights. This can be a real problem. The Plant Hero may be a mutant, a modified plant, a member of a species of intelligent plant life, or a human or other being who was somehow transformed into a plant. A permanent result of Induced Vegetation could create such a character. Man-Thing is an example of the last type. Plants automatically possess Absorption Power of Good rank in the form of enhanced photosynthesis. Plants have no initial Contacts; the exception is if the Plant was created by scientific means, in which case its creator might be a Contact."; }
    },
    AbnormalChemistry("Abnormal Chemistry", 2, 0.01){
        public int getEnduranceBonus(){ return 1; }
        public String getNotes(){ return "<b>Abnormal Biochemistry</b>: The body is apparently normal but possesses a different chemical base than that of Normal Humans. A key element in the body's chemical makeup is replaced by another element. The most common abnormalities are silicon replacing carbon, copper replacing iron, and cobalt replacing iron. Silicon-based life has a body temperature 40 degrees lower than similar carbon-based life.  Copper produces green blood.  Cobalt produces blue blood.  In all these cases, acquiring food that fits the hero's metabolic needs is a problem. If the abnormal lacks a food supply, he'll have to seek one out. A lab of Remarkable cost can synthesize the necessary foodstuffs. For game purposes, assume the hero already possesses a steady food supply.  Because of the different body chemistries, abnormals cannot donate blood or body tissues for transfusion into Normal Humans. Likewise, anything foolish enough to try to feed on the abnormal, like a lion or a Bio-Vampire, takes Good damage as it tries to digest what, to its system, is poison.  Abnormals cannot interbreed easily with Normal Humans, even when their bodies are virtually identical. A hospital with Incredible facilities is needed top after the would-be parent's genetic material to a compatible type."; }
    },
    Mineral("Mineral", 2, 0.01){
        public List<Perk> getPerks(){ return new ArrayList<Perk>(Arrays.asList(Perk.DoubleHP)); }
        public String getNotes(){ return "<b>Mineral Life</b>: The body is composed of solid materials that normally do not sustain life. In fact, the body might not even have anything remotely resembling internal organs. In such cases, an internal examination would only reveal homogenous matter.  The body can be of any single element or compound or a mixture of anything the player can think of. Examples of Mineral Life include golems and Warlock (of the New Mutants).  Because Mineral Life is simpler, it is easier to feed and maintain. If food is needed, the Mineral Life can digest raw matter of its composition. Wounds can be bandaged by applications of the same matter as well. (\"But Doctor, I'm not a bricklayer!\")  Mineral Life is immune to all Poisons and Diseases that harm Normal Humans.  Conversely, exotic poisons and diseases that do harm to Mineral Life do only Feeble damage to Normal Humans.  Mineral Life is vulnerable to attacks with special effects on the body materials. For example, an iron golem is prone to rust. Movement rate is decreased -1CS."; }
    },
    Gaseous("Gaseous", 5, 0.01){
        public List<Perk> getPerks(){ return new ArrayList<Perk>(Arrays.asList(Perk.ZeroResources, Perk.AllAlone)); }
        public String getNotes(){ return "<b>Gaseous Life</b>: The body is completely composed of gases, vapors, smoke, and mist without any solid (or even liquid) components above the microscopic level. The Gas Body is a coherent cloud that retains its integrity even in the face of Amazing Intensity winds. Unlike normal clouds, the Gas Body can more at will in any direction and even penetrate liquids and permeable solids. However, it cannot freely move in a vacuum unless it possesses a Travel or Energy Power. The Gas Body may be composed of a single element or compound or any sort of exotic mixture. If the gaseous hero possesses a Shapechanging Power, Alter Ego, or Body Transformation-Self, the being can temporarily assume a human-like form. Gas Bodies are immobilized if converted to liquid or solid forms but take no damage from this act. While gaseous, the being can freely expand or contract. Minimum size is one cubic foot. The maximum size can fill a volume equivalent to the average shopping mall. On Earth, Gas Bodies have zero Resources and no initial Contacts. The only way to destroy a Gas Body is to alter its composition through Powers like Matter Conversion and Matter Control. Inhaling a Gas Body can be a fatal act since the being's gases can prevent required gases from reaching the lungs. Gas Bodies can enter a symbiotic relationship with a solid being. Gas Bodies possess a natural form of Phasing that permits them to penetrate solids."; }
    },
    Liquid("Liquid", 5, 0.01){
        public List<Perk> getPerks(){ return new ArrayList<Perk>(Arrays.asList(Perk.JustOneFriend)); }
        public List<Contact> getForcedContacts(){ return new ArrayList<Contact>(Collections.singletonList(new Contact("Race"))); }
        public String getNotes(){ return "<b>Liquid Life</b>: You know that the Normal Human body is 68% liquid? Well, this type is 100% liquid. However, it is composed of special liquids that remain together. The fluid body can be of any viscosity from gelatinous to watery. It can move at will by flowing through other liquids or along surfaces. It can even climb vertical surfaces. If the liquid life possesses Endurance and Psyche ranks of Excellent or better, the Fluid Body can form an erect simulation of a human body. This can \"walk\" by sliding along the ground. Contrary to what you might think, a Fluid Body is actually dry to the touch. This is because none of the body's liquids leave the body unless deliberately secreted. The Fluid Body can be housed in a .naturally secreted sac or in an artificial container. This is determined by the player rolling such Powers as Armor, Body Armor, or Body Coating. If the Fluid Body is frozen, the hero is immobilized until he can melt. He takes no damage from such an attack, although sacs or body containers might be shattered by the cold. Vaporization is a fatal act for most Fluid Bodies.  Fluid Bodies have a natural variation of Phasing that permits them to permeate any porous material.  Fluid Bodies have no initial Contacts except their own race, if one exists.  Because of the Fluid Bodies' control over their own fluids, it requires an Incredible Agility FEAT to drain off any part of the Fluid Body. Drained parts remain under the main body's control as long as they are within one area. Once beyond that limit, the drained liquid \"dies\" and becomes inert. Swallowing a Fluid Body can be a fatal act if the body so chooses. It can also result in a symbiosis if the Fluid Body takes a liking to the solid host."; }
    },
    Energy("Energy", 5, 0.01){
        public List<Perk> getPerks(){ return new ArrayList<Perk>(Arrays.asList(Perk.EnergyBeing)); }
        public String getNotes(){ return "<b>Energy Body</b>: The hero is a field of coherent energy. The basis for this can be any Energy form found in the Energy Emission and Control sections of this book. The Energy Body can move at will in any direction, even though spaces that lack a medium to transmit it. The Energy Body possesses an Intensity rank of its own; this is how the Health points apply to this being.  Energy Bodies follow the same characteristics as normal energy of the same type. They possess a special vulnerability to Plasma C control I -1CS Resistance). Energy Bodies can be contained within special storage batteries; this is the only way to immobilize these beings.  Energy Bodies composed of visible energy types can create a ghost-like image of a human. If the Energy Body possesses Alter Ego, Energy Solidification, or Lifeform Creation, it can form a solid facsimile of a human.  The only way to destroy an Energy Body is to completely Negate or solidify its energy. Physical contact with an Energy Being does Feeble damage."; }
    },
    Ethereal("Ethereal", 1, 0.01){
        public String getNotes(){ return "<b>Ethereal</b>: The hero is an intangible, disembodied spirit. He can be a ghost who once possesses a mortal shell, or belong to a race that always exists in this form. An Ethereal can drift about in any direction he chooses, and can pass through solid matter without any effort. The visibility of an Ethereal varies according to his whim; he can be invisible, transparent, translucent, or opaque. If the Ethereal is a ghost, his form resembles an idealized version of his old body. The ghost's appearance is actually based on his self-image and thus reflects the ghost's attitude toward himself. This is why ghosts are usually either very beautiful (or handsome) or quite pathetic. Ghosts are immune to most physical attacks with Intensities less than Unearthly. They are vulnerable to Mental and Magical attacks, especially by Powers that affect the spirit. Either Psi or Spirit Vampirism can destroy an Ethereal.  While Ethereals are intangible on the Earth Dimension, they regain solidity in other Dimensions. In such realms Ethereals are vulnerable to all Powers except those that specifically affect Ethereals and other disembodied beings; these Powers are Spirit Summoning and Storage, Reincarnation, and Exorcism.  If the Ethereal once had a solid body, he might not necessarily have died to reach his current state. He might have become an Ethereal by being directly transformed from solidity to ethereality. Such transformations can be magical, scientific, Powerbased, accidental, or deliberate. The Red Ghost is an example of a Normal Human directly transformed into an Ethereal as a result of a scientific mishap.  If the Ethereal possesses Alter Ego or Lifeform Creation, he can create a living body for himself. If he possesses Mental Domination, he can possess a human host.  Fighting rank is zero in the Earth Dimension, unless the Ethereal is fighting another Ethereal.  Physical attacks have a decreased effect on Ethereals (-9CS).  Spirit Vampirism completely destroys Ethereals. Psi-Vampirism destroys the self-image and reduces the Ethereal to a mindless Poltergeist.  At least one Contact can be a Spiritual Medium."; }
    },
    Undead("Undead", 1, 0.01){
        public int getStrengthBonus(){ return 1; }
        public int getEnduranceBonus(){ return 1; }
        public String getNotes(){ return "<b>Undead</b>: The being in question had once been a Normal Human (or any other species) but has since died. Through some arcane and possibly disgusting means, the body has regained animation and ceased to decay. The being's life force is once again in residence (although the old house just isn't the same). Special means are required to maintain the reunion of mind and body.  This can be anything from being frequently re-embalmed to utilizing any of the Vampiric Powers. If the Undead fails to follow his required - maintenance procedures, he begins to fall apart. In Undead terms, this is what Health points are used for. Health is the structural integrity of the Undead's own corpse.  The nature of the Undead can vary.  Examples include Bio-Vampires like Dracula, Zombies (\"Zuvembies\" in the Marvel Universe), animate Mummies like those in ancient pyramids and bad B-movies, and even hybrid forms that still retain some humanity. Dracula's daughter Lilith is such a being, being conceived after Dracula had become an Undead.  Technical note: At this time, all Bio-Vampires on the Marvel Universe Earth have been destroyed. Your campaign, however, can be free of this restriction if you so desire. The Great Continuity Goddess bade me mention it anyway. Strength and Endurance are increased by +1CS.  The player and Judge must come up with a body maintenance procedure, unless the hero possesses a Vampiric Power.  Undead possess a Psychological Weakness; their Power is negated while they are within 10' of a religious symbol.  If the symbol is that of a religion the Undead practiced while he was alive, he suffers Excellent damage."; }
    },
    Compound("Compound", 1, 0.01){
        public String getNotes(){ return "<b>Compound Form</b>: The hero's body contains aspects of two or more of the preceding Body Types. As such, it possesses a mixture of the advantages and disadvantages of each type. The Combination of advantage and disadvantage is unique to each Compound.  When creating a Compound character, the player first generates the number of Body Types combined in his character, then the actual types, using the Body Type Table above. The next step is determining the advantages and disadvantages are retained by the compound. Example: The dice have assigned the hero a Compound Body Type. Muttering under his breath (\"Great, I get to play a freak\"), the player rolls a 61. His Compound has three aspects, which the dice again decide16 (Normal Human), 69 (Chiropteran), and 72 (Other Demihuman). Three Body Types get him a 33% chance of retaining advantages and disadvantages. He starts rolling. By the time he's done, his freak has begun to form. The character's wings sprout from his back, rather than being formed by his arms. The ears are smaller and more human-like since he lacks sonar. From the Other Demihuman aspect, a waspman, he gets a stinger that does Excellent Paralysis damage and rigid plates on his torso. The artificial Body Types lend themselves especially well to creating Compounds. All such Compounds are automatically Cyborgs. Compounds only roll on a single column, determined by the A/D percentage. Most Compounds are unique individuals. Due to their peculiar nature, they do nor easily reproduce. Genetic offspring, including clones, possess only a single aspect. In the example, a clone of the freak would be either a Normal Human, Chiropteran, or wasp- man. Popularity is decreased -1CS, cumulative with any losses determined by the various aspects (Body Types)."; }
        public String getPlayerNotes(){ return "The player needs to generate a number of forms and what those are for their Physical Form."; }
    },
    Changeling("Changeling", 1, 0.01){
        public String getNotes(){ return "<b>Changeling</b>: The hero can transform into any of a number of possible Body Types. Each Body Type aspect of the Changeling possesses its regular advantages and disadvantages which apply only when the hero is in that particular form. What powers the hero possesses are assigned to any and all of his Aspects. Each Aspect must have one Power which is unique to it, a Power no other Aspect has. The hero can transform himself from one Aspect to another in 10 turns. During this time, no Powers can function and all Primary Abilities temporarily drop -2CS. Changeling is similar to the Power of Alter Ego. If the player rolls that Power while creating a Changeling character, he can discard it and roll another Power.  Example: Kit has rolled Changeling for his Body Type. This one has two Aspects: 83, Humanshape Robot, and 91, Vegetable. \"Great, a robot that turns into Man-Thing.\" Eventually, Kit decides his robot was specially designed to imitate other life-forms, but the Shapechange circuitry burned out after recording its first form.  If while in one Aspect the hero loses all Health points, he can save his life by making a red Psyche FEAT. Success means he lives, but permanently loses the ability to transform into that Aspect.  Powers can be assigned to any or all Aspects. Each Aspect must have a unique Power not shared with other Aspects."; }
        public String getPlayerNotes(){ return "The player needs to generate a number of forms and what those are for their Physical Form."; }
    },
    ;
    public static PhysicalForm random(){
        double val = Math.random();
        for (PhysicalForm form: values()){
            val -= form.probability;
            if (val <= 0) return form;
        }
        return values()[0];
    }

    private String name;
    private double probability;
    private int randomRanksColumn;

    private PhysicalForm(String name, int randomRanksColumn, double probability){
        this.name = name;
        this.randomRanksColumn = randomRanksColumn;
        this.probability = probability;
    }

    public String getName(){ return name; }
    public int getRandomRanksColumn(){ return randomRanksColumn; }
    public int getFightingBonus(){ return 0; }
    public int getAgilityBonus(){ return 0; }
    public int getStrengthBonus(){ return 0; }
    public int getEnduranceBonus(){ return 0; }
    public int getReasonBonus(){ return 0; }
    public int getIntuitionBonus(){ return 0; }
    public int getPsycheBonus(){ return 0; }
    public int getResourcesBonus(){ return 0; }
    public int getPopularityBonus(){ return 0; }
    public int getNumberOfPowersBonus(){ return 0; }
    public int getBonusAbilityRanks(){ return 0; }
    public List<Perk> getPerks(){ return new ArrayList<Perk>(); }
    public List<Power> getForcedPowers(){ return new ArrayList<Power>(); }
    public List<Contact> getForcedContacts(){ return new ArrayList<Contact>(); }
    public String getNotes(){ return null; }
    public String getPlayerNotes(){ return null; }

}
